# values for server.
server:
  replicaCount: 1

  image:
    repository: helloworld-server
    pullPolicy: IfNotPresent
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 8086
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  ingress:
    enabled: false

# values for client.
client:
  replicaCount: 1
  image:
    repository: helloworld-client
    pullPolicy: IfNotPresent
    tag: latest

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  service:
    type: ClusterIP
    port: 8082
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  ingress:
    enabled: false